# Generated by Django 5.2 on 2025-05-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='for_sale',
            field=models.BooleanField(default=False, verbose_name='На продажу?'),
        ),
    ]
