# Generated by Django 5.2 on 2025-05-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projects_for_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
